#ifndef CONST_H_
#define CONST_H_
#define POS_X_INITIALLE 0
#define POS_Y_INITIALLE 0
#define ANGLE_INITIAL 0
#define ENTRAXE_TICK 6826.0//13652.0
#define ASSERV_MAX_INTEGRALE_DST 50000
#define ASSERV_MAX_INTEGRALE_ANG 30000
#define FREQUENCE_IT 10
#endif /* CONST_H_ */
